title: "gh-pr-phase-monitor"
description: "gh-pr-phase-monitor"
theme: jekyll-theme-slate
github:
  is_project_page: true
  repository_url: https://github.com/cat2151/gh-pr-phase-monitor
plugins:
  - jekyll-sitemap
